name: Youthall Notifier

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch: 

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.5"

      - name: Gereksinimleri yükle
        run: pip install -r requirements.txt

      - name: Ortam değişkenlerini ayarla
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: python youthall_scraper.py
